### ISSUE TITLE
Creating a new document (eg Avalonia Window or Avalonia UserControl) shows "The document is already open" dialog

### ISSUE THREAD

**Issue by derekantrican** [AvaloniaUI/AvaloniaVS#171]
Repo:

1. Right-click project and choose "Add" > "Class"
2. Choose "Window (Avalonia)" or "UserControl (Avalonia)"
3. Click "Add"
4. A dialog pops up saying "The document [document name] is already open. Do you want to close it?"

![image](https://user-images.githubusercontent.com/1558019/93281900-fc107400-f781-11ea-8868-32f70216ba19.png)

**Comment by grokys** [comment]
This is caused by a change in VS16.6 which causes VS to give us an uninitialized object: see https://github.com/AvaloniaUI/AvaloniaVS/pull/146

The fix is to go to `Tools -> options -> environment -> preview features` and uncheck `Load projects faster (some features might be delayed)`.

There is supposed to be [a way to stop this happening](https://gitter.im/Microsoft/extendvs?at=5f04be57a9378637e8b2ca25) but I've not managed to get it working (and ofc all this is undocumented).

Before I disabled this feature I also saw this happening with plain C# files (though I imagine that's now been fixed) so I don't think it affects just us.

**Comment by derekantrican** [comment]
I do not have that option in Preview Features. I only have one option turned on in Preview Features and that's `Use compact menu and search bar`. I'm running VS 2019 version 16.5.0

**Comment by grokys** [comment]
For anyone who might want to try to fix this: the dialog is caused by this bit of code:

https://github.com/AvaloniaUI/AvaloniaVS/blob/master/AvaloniaVS/Services/EditorFactory.cs#L190-L195

**Comment by amwx** [comment]
I think this issue can be closed. I haven't seen this happen and my EditorFactory PR should've fixed all the initialization nonsense so I think this is good now?
