### ISSUE TITLE
Previewer not work after updating axaml in avalonia 11.0.0-rc1.1

### ISSUE THREAD

**Issue by liugangnhm** [AvaloniaUI/AvaloniaVS#334]
![image](https://github.com/AvaloniaUI/AvaloniaVS/assets/743845/a5ca389f-ee3f-4b35-a389-61071051fe14)

```xml
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.0.0-rc1.1" />
    <PackageReference Include="Avalonia.Desktop" Version="11.0.0-rc1.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.0.0-rc1.1" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.0.0-rc1.1" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.0.0-rc1.1" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.0" />
  </ItemGroup>
```

**Comment by maxkatz6** [comment]
Please attach logs from Avalonia Diagnostics tab.
![image](https://github.com/AvaloniaUI/AvaloniaVS/assets/3163374/045901b9-f2b6-41ee-9c0d-ad259c121ba2)


Previewer works for me with RC1. Also double check that you have latest version of plugin.
![image](https://github.com/AvaloniaUI/AvaloniaVS/assets/3163374/4de0f67b-3461-48c5-890b-93fd890860c8)

**Comment by liugangnhm** [comment]
Microsoft Visual Studio Community 2022 (64 位) - 17.6.2

**Comment by liugangnhm** [comment]
Microsoft Visual Studio Community 2022 (64 位) - 17.6.2

**Comment by NoizeDaemon** [comment]
I got the same issue:

• Created a new project with `dotnet new avalonia.xplat -o PreviewerSample`
• Build Solution
• Changing one thing in the XAML updates in the previewer, changing a second thing breaks the previewer (no error or red ! in the corner, but just a transparent frame)
• Running the app and returning reloads the previewer until 2 changes are made

VS 2022 Version: 17.4.4

Avalonia for VisualStudio 2022 Version: 0.10.18.3
All package versions including Diagnostics: 11.0.0-rc1.1

Diagnostics does not show anything special:

```
11:26:53.323 [Information]  Starting previewer process for '"...\PreviewerSample\PreviewerSample.Desktop\bin\Debug\net7.0\PreviewerSample.Desktop.dll"'
11:26:53.329 [Information] 3616 Started previewer process for '"...\PreviewerSample\PreviewerSample.Desktop\bin\Debug\net7.0\PreviewerSample.Desktop.dll"'. Waiting for connection to be initialized.
11:26:53.517 [Information] 3616 Connection initialized
```

Pretty sure it's not necessary since the reproduction steps are quite few, but here's a [minimal sample](https://github.com/NoizeDaemon/PreviewerSample)!


(I made this video before I found this discussion, it basically just shows the same effect as the one by the previous poster.)
https://github.com/AvaloniaUI/AvaloniaVS/assets/42150677/3840a95d-2dac-4f4f-914b-7c88f35b0c54


Not sure if that's possible, but as a temporary workaround it could be nice to have a hotkey to reload (stop/start) the previewer.

**Comment by liugangnhm** [comment]
and i found Rider has the same issue

**Comment by Eugenenoble2005** [comment]
No work around yet? Avalonia is kinda deadbeat without the xaml previewer working

**Comment by Eugenenoble2005** [comment]
> and i found Rider has the same issue

I have the same issue as you as well on visual studio. Seems to be working on rider

**Comment by Eugenenoble2005** [comment]
I can also confirm the latest PR build has gotten the previewer working in visual studio
