### ISSUE TITLE
Visual Studio Professional 2022 crashing on .axaml files

### ISSUE THREAD

**Issue by soerenlemke** [AvaloniaUI/AvaloniaVS#389]
**Describe the bug**
Visual Studio Professional 2022 coming up with an error when double clicking on an .axaml file. I can run the App without errors, but i can´t view the axaml code. I have the Avalonia extension installed like it is described in the installation guide: https://docs.avaloniaui.net/docs/next/get-started/install 

Here is the message that shows (HRESULT: 0x8000FFFF E_UNEXPECTED):

![image](https://github.com/AvaloniaUI/Avalonia/assets/61249756/b445d98f-f546-45cb-b19c-684aaba33107)

**To Reproduce**
1. Open Visual Studio Professional 2022
2. Double click any .axaml file
3. Error message coming up
(i get the errors even with the example projects: https://github.com/AvaloniaUI/Avalonia.Samples)

**Expected behavior**
VS opening the file like it does in Visual Studio Community 2022. 

**Desktop (please complete the following information):**

- OS: Windows
- Windows 10 Enterprise, Version 22H2, Build: 19045.3448
- IDE: Microsoft Visual Studio Professional 2022 (64-Bit) - Current, Version 17.0.0

**Comment by Takoooooo** [comment]
May you please try this VSIX and check if it fixes the issue for you. I don't have the VS Pro by the hand and can't verify whether it fixes the issue or not. In case when it doesen't fix your issue i would be keen if you would clone that repo and run it on VS Pro Experimental instance because i might need more information
[AvaloniaVS.VS2022 (10).zip](https://github.com/AvaloniaUI/AvaloniaVS/files/12751005/AvaloniaVS.VS2022.10.zip)

**Comment by soerenlemke** [comment]
Thank you for the reply! I deinstalled my Visual Studio Current Version and installed a "normal" Visual Studio Professional 2022 version. With the newest updates everything works fine :) I don't know how to reproduce the errors because I had that Current version of Visual Studio installed and don't have it anymore...
