### ISSUE TITLE
Visual Studio 2019 Integration

### ISSUE THREAD

**Issue by f-lima** [AvaloniaUI/AvaloniaVS#96]
Unlike show at Avalonia website, there is no option to create a UserControl in the options of Visual Studio 2019 (File -> Add -> New File).

Either there is no option to edit or view the form created, the preview stay blank.

I don't know if it is related of version VS 2019 or any other configuration.

**Comment by grokys** [comment]
I don't see a `File -> Add -> New File` menu in VS2019

![image](https://user-images.githubusercontent.com/1775141/57027905-ef978400-6c3d-11e9-888b-d38fec279656.png)

Is this menu item being added by another extension by any chance?

**Comment by danwalmsley** [comment]
File -> NewFile ?

**Comment by patrick-a-cavanaugh** [comment]
I had this problem but it was because in VS 2019 I had my solution explorer displaying my project's files, rather than the default solution explorer view. Once I switched back from file view to solution view, the "Add Item" menu includes "User Control (Avalonia)" and "Window (Avalonia)" as shown in the tutorial.
